export const OEUVRE_TYPES = {

    "ADD_OEUVRE_START": "ADD_OEUVRE_START",
    "ADD_OEUVRE_SUCCESS": "ADD_OEUVRE_SUCCESS",
    "ADD_OEUVRE_FAILURE": "ADD_OEUVRE_FAILURE",

    "DELETE_OEUVRE_START": "DELETE_OEUVRE_START",
    "DELETE_OEUVRE_SUCCESS": "DELETE_OEUVRE_SUCCESS",
    "DELETE_OEUVRE_FAILURE": "DELETE_OEUVRE_FAILURE",

    "MODIFIER_OEUVRE_START": "MODIFIER_OEUVRE_START",
    "MODIFIER_OEUVRE_SUCCESS": "MODIFIER_OEUVRE_SUCCESS",
    "MODIFIER_OEUVRE_FAILURE": "MODIFIER_OEUVRE_FAILURE",

    "GET_OEUVRE_BY_ID_START": "GET_OEUVRE_BY_ID_START",
    "GET_OEUVRE_BY_ID_SUCCESS": "GET_OEUVRE_BY_ID_SUCCESS",
    "GET_OEUVRE_BY_ID_FAILURE": "GET_OEUVRE_BY_ID_FAILURE",

    "LIST_OEUVRE_START": "LIST_OEUVRE_START",
    "LIST_OEUVRE_SUCCESS": "LIST_OEUVRE_SUCCESS",
    "LIST_OEUVRE_FAILURE": "LIST_OEUVRE_FAILURE",


}
