export const USER_TYPES = {
    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT: 'LOGOUT',
    REGISTER_START: 'REGISTER_START',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
    MODIFIER_START: 'MODIFIER_START',
    MODIFIER_SUCCESS: 'MODIFIER_SUCCESS',
    MODIFIER_FAILURE: 'MODIFIER_FAILURE',

    ADMIN_ADD_USER_START: 'ADMIN_ADD_USER_START',
    ADMIN_ADD_USER_SUCCESS: 'ADMIN_ADD_USER_SUCCESS',
    ADMIN_ADD_USER_FAILURE: 'ADMIN_ADD_USER_FAILURE',

    ADMIN_DELETE_USER_START: 'ADMIN_DELETE_USER_START',
    ADMIN_DELETE_USER_SUCCESS: 'ADMIN_DELETE_USER_SUCCESS',
    ADMIN_DELETE_USER_FAILURE: 'ADMIN_DELETE_USER_FAILURE',

    ADMIN_MODIFIER_USER_START: 'ADMIN_MODIFIER_USER_START',
    ADMIN_MODIFIER_USER_SUCCESS: 'ADMIN_MODIFIER_USER_SUCCESS',
    ADMIN_MODIFIER_USER_FAILURE: 'ADMIN_MODIFIER_USER_FAILURE',

    ADMIN_LIST_USER_START: 'ADMIN_LIST_USER_START',
    ADMIN_LIST_USER_SUCCESS: 'ADMIN_LIST_USER_SUCCESS',
    ADMIN_LIST_USER_FAILURE: 'ADMIN_LIST_USER_FAILURE',

    GET_USER_START: 'GET_USER_START',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAILURE: 'GET_USER_FAILURE',

    RESET_PASSWORD_START: 'RESET_PASSWORD_START',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',




}
